### ISSUE TITLE
[CHORE] API 명세서 정리

### ISSUE THREAD

**Issue by leegwichan** [debate-timer/debate-timer-be#16]
### ✨ Description

- 12.12  BE 회의를 바탕으로 API 명세서 정리

### ✨ Time(마감기한)

- ~ 12.12까지

### 기타

- https://www.notion.so/API-15a1550c60cf80999e7edbc1caa1b1e4

**Comment by coli-geonwoo** [comment]
/noti

고생많았어요 커찬 😄 

- POST / DELETE api에서 파라미터인 tableId와 memberId도 표로 정리하여 설명 추가했습니다.
![image](https://github.com/user-attachments/assets/de9bd3a1-09fd-4b61-bced-04cf07d57907)

- [질문] table 업데이트(PATCH)api가 해당 id의 table을 전체 삭제하고 덮어씌우는 방식이라면 **patch보다 put이 더 알맞을 수도 있을 것 같은데 restful api 관점에서 각자의 의견이 어떠한지** 궁금해요?

**Comment by leegwichan** [comment]
/noti

> [질문] table 업데이트(PATCH)api가 해당 id의 table을 전체 삭제하고 덮어씌우는 방식이라면 patch보다 put이 더 알맞을 수도 있을 것 같은데 restful api 관점에서 각자의 의견이 어떠한지 궁금해요

오랜만에 PUT 과 PATCH의 차이를 찾아봤네요;; (한 만 2년 전에 공부했던 것 같은데;;)
PUT 좋을 것 같아요. 모든 타임박스를 다 지우고 다시 생성한다는 관점에서 봤을 때 좋겠네요!

[참고 자료]
[HTTP 메서드 :: PUT과 PATCH의 차이](https://blog.naver.com/ghdalswl77/222718562135)
